### ISSUE TITLE
由于汉字编码有好几种 得明确一下采用的是UTF-8还是GB2312 建议采用UTF-8

### ISSUE THREAD

**Issue by mysterywolf** [XYX12306/solar_terms#1]
可以使用这个工具格式化一下代码 https://github.com/mysterywolf/formatting

**Comment by XYX12306** [comment]
> 可以使用这个工具格式化一下代码 https://github.com/mysterywolf/formatting
多谢提醒！我是用VS Code编辑源码，编码选择的是UTF-8，每次修改完都点一下内置的“格式化文档”，保存提交

**Comment by mysterywolf** [comment]
建议在readme中明确出来，否则终端解码可能会乱码
